# Generated by Django 4.0.4 on 2022-08-11 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Company_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('Email_id', models.EmailField(max_length=50)),
                ('Company_code', models.CharField(max_length=5, null=True, unique=True)),
                ('Strength', models.IntegerField(null=True)),
                ('Website', models.URLField(null=True)),
                ('Created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
